# vim: et sr sw=2 ts=2 smartindent:

# The db destination to hold the results
db:
  table_name: customer_orders
  conn_str: "host=127.0.0.1 password=postgres user=postgres dbname=warehouse"

# Where to get the source parquet files, and how many at once to download
s3:
  bucket: "customer-orders-parquet"
  download_batch_size: 4
  downloads_dir: "local/out" # assumes binary is run from repo root dir

# The parquet files contain a lot of columns. Which ones do we need to write to the db?
parquet:
  desired_fields:
    - order_id
    - desc
    - some_unsigned_float
    - some_positive_int

parquet_to_db:
  order_id: id
  desc: description

work_lists:
  dir: "local/work" # assumes binary is run from repo root dir
