---
# You can test hooks manually without committing anything
# pre-commit run <hook name> --all-files
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-symlinks
      - id: detect-aws-credentials
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.4
    hooks:
      - id: forbid-crlf
      - id: forbid-tabs
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: shellcheck
  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo-fmt
        always_run: true
        args: ["--"]
        entry: cargo fmt
        language: system
        pass_filenames: false
        types: [rust]
      - id: cargo-clippy
        name: cargo-clippy
        always_run: true
        args: ["--"]
        entry: cargo clippy --all-targets
        language: system
        pass_filenames: false
        types: [rust]

exclude: |
    (?x)(
        ^tests/testdata/unit-tests/work_lists
    )
